// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "learn-unit-testing/entity"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// IDiscount is an autogenerated mock type for the IDiscount type
type IDiscount struct {
	mock.Mock
}

// Insert provides a mock function with given fields: _a0, _a1, _a2
func (_m *IDiscount) Insert(_a0 context.Context, _a1 *sqlx.Tx, _a2 entity.Discount) (entity.Discount, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 entity.Discount
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.Discount) entity.Discount); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(entity.Discount)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, entity.Discount) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
