// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "learn-unit-testing/entity"

	mock "github.com/stretchr/testify/mock"
)

// IProduct is an autogenerated mock type for the IProduct type
type IProduct struct {
	mock.Mock
}

// Detail provides a mock function with given fields: _a0, _a1
func (_m *IProduct) Detail(_a0 context.Context, _a1 string) (entity.Product, error) {
	ret := _m.Called(_a0, _a1)

	var r0 entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
